"""Repository and profile-related domain ports."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Protocol


class CityRepositoryPort(Protocol):
    """Port for city data repository operations."""

    @property
    def db_path(self) -> Path: ...

    @property
    def hungarian_db_path(self) -> Path: ...

    def validate_paths(self) -> bool: ...
    def get_cities_for_region(
        self,
        mapped_region: str,
        original_region: str,
        country_codes: List[str],
        limit: int,
        hungarian_mapping: Dict[str, str],
    ) -> List[Dict[str, Any]]: ...
    def search_cities(self, query: str, limit: int = 20) -> List[Dict[str, Any]]: ...
    def autocomplete_city_name(
        self, query: str, limit: int = 20
    ) -> List[Dict[str, Any]]: ...
    def get_city_by_id(self, city_id: int) -> Optional[Dict[str, Any]]: ...
    def get_city_by_coordinates(
        self,
        latitude: float,
        longitude: float,
    ) -> Optional[Dict[str, Any]]: ...
    def close(self) -> None: ...


class AnomalyProfilePort(Protocol):
    """Port for anomaly profile management operations."""

    def get_active_profile(self) -> Dict[str, Any]: ...
    def get_profile(self, profile_name: str) -> Optional[Dict[str, Any]]: ...
    def get_all_profiles(self) -> List[Dict[str, Any]]: ...
    def create_profile(self, name: str, data: Dict[str, Any]) -> bool: ...
    def update_profile(self, name: str, data: Dict[str, Any]) -> bool: ...
    def delete_profile(self, name: str) -> bool: ...
